# client-setup.conf — VM name mappings for client-sim
# Section name = c<vmid>, key = vm_name
# Used by clone.sh and check_guest.sh via ini-parser.sh
# Add a new entry for each VM in your environment.

[c90001]
vm_name=slynch

[c90002]
vm_name=hmorton

[c90003]
vm_name=bchan

[c90004]
vm_name=bpace

[c90005]
vm_name=emccarty

[c90006]
vm_name=mforbes

[c90007]
vm_name=mhanson

[c90008]
vm_name=jjenkins

[c90009]
vm_name=klarsen

[c90010]
vm_name=lharrington

[c90011]
vm_name=dkhan

[c90012]
vm_name=bstephenson

[c90013]
vm_name=ohartman

[c90014]
vm_name=amoran

[c90015]
vm_name=krodgers

[c90016]
vm_name=qdunn

[c90017]
vm_name=hcalhoun

[c90018]
vm_name=cblair

[c90019]
vm_name=narroyo

[c90020]
vm_name=froth

[c90021]
vm_name=itaylor

[c90022]
vm_name=bolson

[c90023]
vm_name=agregory

[c90024]
vm_name=dshelton

[c90025]
vm_name=caustin

[c90026]
vm_name=pkoch

[c90027]
vm_name=jjohnston

[c90028]
vm_name=hturner

[c90029]
vm_name=lolsen

[c90030]
vm_name=smeadows

[c90031]
vm_name=vallen

[c90032]
vm_name=nhudson

[c90033]
vm_name=orowland

[c90034]
vm_name=kdurham

[c90035]
vm_name=lreilly

[c90036]
vm_name=ppacheco

[c90037]
vm_name=astanton

[c90038]
vm_name=kbrown

[c90039]
vm_name=cserrano

[c90040]
vm_name=pnewman

[c90041]
vm_name=acain

[c90042]
vm_name=asparks

[c90043]
vm_name=mwhite

[c90044]
vm_name=cfaulkner

[c90045]
vm_name=breid

[c90046]
vm_name=dvance

[c90047]
vm_name=bberry

[c90048]
vm_name=tgilbert

[c90049]
vm_name=jdaniels

[c90050]
vm_name=dandrade

[c90051]
vm_name=shodges

[c90052]
vm_name=dwebster

[c90053]
vm_name=rhudson

[c90054]
vm_name=bmccormick

[c90055]
vm_name=gbarnett

[c90056]
vm_name=lshah

[c90057]
vm_name=ewalls

[c90058]
vm_name=mbeck

[c90059]
vm_name=calvarez

[c90060]
vm_name=candersen

[c90061]
vm_name=kcantu

[c90062]
vm_name=pmcintyre

[c90063]
vm_name=elandry

[c90064]
vm_name=gperez

[c90065]
vm_name=lirwin

[c90066]
vm_name=lnolan

[c90067]
vm_name=dlewis

[c90068]
vm_name=edunn

[c90069]
vm_name=jwoodward

[c90070]
vm_name=onixon

[c90071]
vm_name=achung

[c90072]
vm_name=drussell

[c90073]
vm_name=mglover

[c90074]
vm_name=ejennings

[c90075]
vm_name=dhill

[c90076]
vm_name=ccastaneda

[c90077]
vm_name=fbest

[c90078]
vm_name=mberger

[c90079]
vm_name=dtaylor

[c90080]
vm_name=rcamacho

[c90081]
vm_name=sballard

[c90082]
vm_name=jprince

[c90083]
vm_name=gcollier

[c90084]
vm_name=jparrish

[c90085]
vm_name=cmathis

[c90086]
vm_name=chull

[c90087]
vm_name=phale

[c90088]
vm_name=dmatthews

[c90089]
vm_name=epittman

[c90090]
vm_name=lrichmond

[c90091]
vm_name=schandler

[c90092]
vm_name=ebonilla

