[simulation]
kill_switch=off
rapid_update=on
sim_load=100
github_repo=on
repo_location=https://github.com/solutions-hpe/client-sim/
repo_branch=main
smb_repo=off
site_based_ssid=on
reboot_schedule=300
allow_offline=no
ssidpw_fail=off
auth_fail=off
dot1x_password=password
dot1x_eap=peap
iperf_bw=1k
syslog=on
web_server=on

[server]
server_url=http://169.253.1.1:8000

[address]
smb_address=//nas/scripts
ping_address=172.31.201.3
dns_latency_1=13.239.88.95
dns_latency_2=27.110.152.250
dns_latency_3=165.246.10.2
dns_bad_ip_1=10.252.0.1
dns_bad_ip_2=172.16.252.1
dns_bad_ip_3=192.168.252.1
dns_bad_record_1=10.79.254.90
dns_bad_record_2=10.79.254.91
dns_bad_record_3=10.0.0.10
iperf_server=172.31.201.135
syslog_server=169.253.1.5

[s0]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=off
assoc_fail=off
port_flap=off
ping_test=on
download=off
www_traffic=on
iperf=off
sim_phy=wireless
l1=no

[s1]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=off
assoc_fail=on
port_flap=off
ping_test=off
download=off
www_traffic=on
iperf=off
sim_phy=wireless
l1=no

[s2]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=off
assoc_fail=on
port_flap=off
ping_test=off
download=off
www_traffic=off
iperf=off
sim_phy=wireless
l1=no

[s3]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=on
assoc_fail=off
port_flap=off
ping_test=on
download=on
www_traffic=on
iperf=off
sim_phy=wireless
l1=no

[s4]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=on
assoc_fail=off
port_flap=off
ping_test=on
download=off
www_traffic=on
iperf=off
sim_phy=wireless
l1=no

[s5]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=on
assoc_fail=off
port_flap=off
ping_test=on
download=on
www_traffic=off
iperf=off
sim_phy=wireless
l1=no

[s6]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=on
assoc_fail=off
port_flap=off
ping_test=on
download=off
www_traffic=on
iperf=off
sim_phy=wireless
l1=no

[s7]
wsite=MIA
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=off
assoc_fail=off
port_flap=off
ping_test=on
download=on
www_traffic=off
iperf=off
sim_phy=wireless
l1=no

[s8]
wsite=DFW
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=on
assoc_fail=off
port_flap=off
ping_test=on
download=on
www_traffic=on
iperf=off
sim_phy=wireless
l1=no

[s9]
wsite=DFW
ssid=PSK
ssidpw=PassW0rd!
dhcp_fail=off
dns_fail=off
assoc_fail=off
port_flap=off
ping_test=on
download=on
www_traffic=on
iperf=off
sim_phy=wireless
l1=no
