$InputFileName /usr/local/scripts/sim.log
$InputFileTag client-sim
$InputFileStateFile stat-client-sim
$InputFileSeverity info
$InputFileFacility local7
$InputFilePollInterval 1
$InputFilePersistStateInterval 1
$InputRunFileMonitor