module(load="imfile" PollingInterval="1")

input(type="imfile"
      File="/usr/local/scripts/sim.log"
      Tag="client-sim"
      Severity="info"
      Facility="local7"
      PersistStateInterval="1")
